[package]
name = "stellr-app"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "stellr"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
axum = "0.8"
clap = { version = "4", features = ["derive"] }
getrandom = "0.3"
serde.workspace = true
serde_json.workspace = true
stellr-core = { path = "../core" }
stellr-github = { path = "../github" }
stellr-server = { path = "../server" }
tauri.workspace = true
tauri-plugin-deep-link.workspace = true
tauri-plugin-dialog.workspace = true
tauri-plugin-single-instance.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
async-trait.workspace = true
reqwest = "0.12"
tauri = { workspace = true, features = ["test"] }
tempfile = "3"
tokio.workspace = true

[build-dependencies]
tauri-build.workspace = true
